logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.myapp: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: logs/myapp.log
